classdef erg_recovery < handle
    % concatenate all results from recovery after bleaching, after screening
    % has been completed
    properties
        % path
        id
        isi = 1.5;
        d1results = struct(...
            't',[],...
            'La_peak',[],...
            'Lb_peak',[],...
            'La_ttp',[],...
            'Lb_ttp',[],...
            'Ra_peak',[],...
            'Rb_peak',[],...
            'Ra_ttp',[],...
            'Rb_ttp',[],...
            'Lab_peak',[],...
            'Rab_peak',[]...
            );
        d1tnaught
        d1tdelays
        d1bleachedeye
        d1dirData
        d1dirFile
        d3results = struct(...
            't',[],...
            'La_peak',[],...
            'Lb_peak',[],...
            'La_ttp',[],...
            'Lb_ttp',[],...
            'Ra_peak',[],...
            'Rb_peak',[],...
            'Ra_ttp',[],...
            'Rb_ttp',[],...
            'Lab_peak',[],...
            'Rab_peak',[]...
            );
        d3tnaught
        d3tdelays
        d3bleachedeye
        d3dirData
        d3dirFile
        d1norm = struct('Lab',[],'Rab',[]);
        d3norm = struct('Lab',[],'Rab',[]);
    end
    
    properties (SetAccess = private)
    end
    
    methods
        function ergR=erg_recovery(whichone)
            ergR.id = whichone;
            ergR.recParse(whichone);
            for i = 1:size(ergR.d1dirFile)
                temperg = ERGobj(ergR.d1dirData,ergR.d1dirFile{i});
                tempresults = temperg.results;
                if i<ergR.d1tnaught(1)
                    tempresults.t = tempresults.t - (length(tempresults.t)+ergR.d1tnaught(2))*ergR.isi;
                elseif i==ergR.d1tnaught(1)
                    tempresults.t = tempresults.t - (ergR.d1tnaught(2))*ergR.isi;
                else
                    tempresults.t = tempresults.t + ergR.d1tdelays(i);
                end
                fnames = fieldnames(ergR.d1results);
                for f = 1:length(fnames)
                    ergR.d1results.(fnames{f}) = [ergR.d1results.(fnames{f});tempresults.(fnames{f})];
                end
            end
            for i = 1:size(ergR.d3dirFile)
                temperg = ERGobj(ergR.d3dirData,ergR.d3dirFile{i});
                tempresults = temperg.results;
                if i<ergR.d3tnaught(1)
                    tempresults.t = tempresults.t - (length(tempresults.t)+ergR.d3tnaught(2))*ergR.isi;
                elseif i==ergR.d3tnaught(1)
                    tempresults.t = tempresults.t - (ergR.d3tnaught(2))*ergR.isi;
                else
                    tempresults.t = tempresults.t + ergR.d3tdelays(i);
                end
                fnames = fieldnames(ergR.d3results);
                for f = 1:length(fnames)
                    ergR.d3results.(fnames{f}) = [ergR.d3results.(fnames{f});tempresults.(fnames{f})];
                end
            end
            ergR.recPlot;
        end
        
        function ergR=recPlot(ergR)
            ergR.d1norm.Lab = mean(ergR.d1results.Lab_peak(ergR.d1results.t<0));
            ergR.d1norm.Rab = mean(ergR.d1results.Rab_peak(ergR.d1results.t<0));
            ergR.d3norm.Lab = mean(ergR.d3results.Lab_peak(ergR.d3results.t<0));
            ergR.d3norm.Rab = mean(ergR.d3results.Rab_peak(ergR.d3results.t<0));
            
%             ergR.d1norm.Lab = 1;
%             ergR.d1norm.Rab = 1;
%             ergR.d3norm.Lab = 1;
%             ergR.d3norm.Rab = 1;
            
            f1=getfigH(1);
            set(f1,'YScale','log')
            setLabels(f1,'time (s)','b-wave amplitude (norm)')
            lH=lineH([ergR.d1results.t(1)-100 ergR.d1results.t(end)+100],[1 1],f1);
            lH.linedash;lH.setName('unity');
            
            if ergR.d1bleachedeye == 'R'
                lH=lineH(ergR.d1results.t,ergR.d1results.Rab_peak./ergR.d1norm.Rab,f1);
            elseif ergR.d1bleachedeye == 'L'
                lH=lineH(ergR.d1results.t,ergR.d1results.Lab_peak./ergR.d1norm.Lab,f1);
            else
                lH=lineH(ergR.d1results.t,zeros(size(ergR.d1results.t,f1),f1));
            end
            lH.markers;lH.color([0 0 0]);
            lH.setName('d1');
            if ergR.d3bleachedeye == 'R'
                lH=lineH(ergR.d3results.t,ergR.d3results.Rab_peak./ergR.d3norm.Rab,f1);
            elseif ergR.d3bleachedeye == 'L'
                lH=lineH(ergR.d3results.t,ergR.d3results.Lab_peak./ergR.d3norm.Lab,f1);
            else
                lH=lineH(ergR.d3results.t,zeros(size(ergR.d3results.t,f1),f1));
            end
            lH.markers;lH.color([1 0 0]);
            lH.setName('d3');
            legend('','day1','day3'); 
            legend('boxoff');
        end
        
        function ergR=recParse(ergR,whichone)
            switch whichone
                %MB001 High dose
                case 'Sq1040'
                    ergR.d1tnaught = [2,13];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20171023/20171023_Sq1040_MB001High';
                    ergR.d1dirFile = {...
                        '02_FlashesPre'; ...
                        '03_FlashesPost0s'; ...
                        '04_FlashesPost1min09s'; ...
                        '05_FlashesPost2min38s'; ...
                        '06_FlashesPost4min07s'; ...
                        '07_FlashesPost5min35s'; ...
                        '08_FlashesPost7min05s'; ...
                        '09_FlashesPost8min34s'; ...
                        '11_FlashesPost14min29s'; ...
                        '12_FlashesPost16min12s'; ...
                        };
                    ergR.d1tdelays = [0,0,69,158,247,335,425,514,869,972];
                    
                    ergR.d3tnaught = [2,10];
                    ergR.d3bleachedeye='L';
                    ergR.d3dirData = '20171025/20171025_Sq1040_MB001High';
                    ergR.d3dirFile = {...
                        '02_FlashPre';...
                        '03_FlashPost0s';...
                        '04_FlashPost1min19s';...
                        '05_FlashPost2min53s';...
                        '06_FlashPost4min20s';...
                        '07_FlashPost5min48s';...
                        '08_FlashPost7min14s';...
                        '09_FlashPost8min37s';...
                        '11_FlashPost13min55s';...
                        '12_FlashPost15min23s';...
                        };
                    ergR.d3tdelays = [0,0,79,173,260,348,434,517,835,923];
                case 'Sq928'
                    ergR.d1tnaught = [2,8];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170830/20170830_Sq928_MB001High';
                    ergR.d1dirFile = {...
                        '03_FlashesPre';...
                        '04_FlashesPost0s';...
                        '05_FlashesPost40s';...
                        '06_FlashesPost2min';...
                        '07_FlashesPost3min10s';...
                        '08_FlashesPost4min30s';...
                        '09_FlashesPost6min';...
                        '10_FlashesPost7min20s';...
                        '11_FlashesPost8min30s';...
                        };
                    ergR.d1tdelays = [0,0,40,120,190,270,360,440,510];
                    
                    ergR.d3tnaught = [1,2];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170901/20170901_Squirrel928_MB001High';
                    ergR.d3dirFile = {...
                        '03_FlashesBrighterPre';...
                        };
                    ergR.d3tdelays = [0];
                case 'Sq1006'
                    ergR.d1tnaught = [2,7];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170829/20170829_Sq1006_MB001High';
                    ergR.d1dirFile = {...
                        '04_FlashesPre';...
                        '05_FlashesPost0s';...
                        '06_FlashesPost1min';...
                        '07_FlashesPost2min20s';...
                        '08_FlashesPost4min30s';...
                        '09_FlashesPost6min30s';...
                        '10_FlashesPost7min50s';...
                        };
                    ergR.d1tdelays = [0,0,60,140,270,390,470];
                    
                    ergR.d3tnaught = [2,5];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170831/20170831_Sq1006_MB001High';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost40s';...
                        '05_FlashesPost2min';...
                        '06_FlashesPost2min55s';...
                        '07_FlashesPost3min50s';...
                        '08_FlashesPost4min50s';...
                        '09_FlashesPost5min45s';...
                        '10_FlashesPost6min43s';...
                        '11_FlashesPost7min40s';...
                        '12_FlashesPost8min40s';...
                        '16_FlashesPost18min';...
                        };
                    ergR.d3tdelays = [0,0,40,120,175,230,290,345,403,460,520,1080];
                
                %MB001 Low
                case 'Sq993'
                    ergR.d1tnaught = [2,4];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170829/20170829_Sq993_MB001Low';
                    ergR.d1dirFile = {...
                        '03_FlashesPre';...
                        '04_FlashesPost0s';...
                        '05_FlashesPost1min';...
                        '06_FlashesPost2min30s';...
                        '07_FlashesPost3min55s';...
                        '08_FlashesPost5min';...
                        '09_FlashesPost6min50s';...
                        '10_FlashesPost8min';...
                        
                        };
                    ergR.d1tdelays = [0,0,60,150,235,300,410,480];
                    
                    ergR.d3tnaught = [2,6];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170831/20170831_Sq993_MB001Low';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost40s';...
                        '05_FlashesPost1min30s';...
                        '06_FlashesPost2min25s';...
                        '07_FlashesPost3min30s';...
                        '08_FlashesPost4min30s';...
                        '09_FlashesPost5min28s';...
                        '10_FlashesPost6min25s';...
                        '11_FlashesPost7min27s';...
                        '12_FlashesPost8min20s';...
                        '13_FlashesPost9min20s';...
                        '15_FlashesPost14min20s';...

                        };
                    ergR.d3tdelays = [0,0,40,90,145,210,270,328,385,447,500,560,860];
                %Sq998
                case 'Sq998'
                    ergR.d1tnaught = [2,7];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170830/20170830_Sq998_MB001Low';
                    ergR.d1dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost40s';...
                        '05_FlashesPost1min20s';...
                        '06_FlashesPost2min30s';...
                        '07_FlashesPost3min50s';...
                        '08_FlashesPost4min55s';...
                        '09_FlashesPost6min10s';...
                        '10_FlashesPost7min30s';...
                        '11_FlashesPost8min40s';...
                        };
                    ergR.d1tdelays = [0,0,40,80,150,230,295,370,450,520];
                    
                    ergR.d3tnaught = [2,7];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170901/20170901_Squirrel998_MB001Low';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min17s';...
                        '05_FlashesPost2min45s';...
                        '06_FlashesPost4min06s';...
                        '07_FlashesPost5min32s';...
                        '08_FlashesPost6min57s';...
                        '09_FlashesPost8min25s';...
                        '11_FlashesPost13min50s';...
                        '12_FlashesPost15min40s';...
                        '13_FlashesPost17min0s';...
                        };
                    ergR.d3tdelays = [0,0,77,165,246,332,417,505,830,940,1020];
                
                    
                    
                %Fenretinide
                %Sq990
                case 'Sq990'
                    ergR.d1tnaught = [2,9];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170905/20170905_Sq990_Fenretinide';
                    ergR.d1dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min17s';...
                        '05_FlashesPost2min40s';...
                        '06_FlashesPost4min05s';...
                        '07_FlashesPost5min36s';...
                        '08_FlashesPost7min06s';...
                        '09_FlashesPost8min28s';...
                        '11_FlashesPost13min52s';...
                        '12_FlashesPost15min52s';...
                        };
                    ergR.d1tdelays = [0,0,77,160,245,336,426,508,832,952];
                    
                    ergR.d3tnaught = [2,7];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170907/20170907_Sq990_Fenretinide';
                    ergR.d3dirFile = {...
                        '02b_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min25s';...
                        '05_FlashesPost2min50s';...
                        '06_FlashesPost4min20s';...
                        '07_FlashesPost5min45s';...
                        '08_FlashesPost7min11s';...
                        '09_FlashesPost8min41s';...
                        '11_FlashesPost13min43s';...
                        '12_FlashesPost15min12s';...
                        };
                    ergR.d3tdelays = [0,0,85,170,260,345,431,521,823,912];
                %Sq995
                case 'Sq995'
                    ergR.d1tnaught = [2,7];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170905/20170905_Sq995_Fenretinide';
                    ergR.d1dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min23s';...
                        '05_FlashesPost2min27s';...
                        '06_FlashesPost4min16s';...
                        '07_FlashesPost5min44s';...
                        '08_FlashesPost7min08s';...
                        '09_FlashesPost8min36s';...
                        '11_FlashesPost13min47s';...
                        '12_FlashesPost15min20s';...
                        };
                    ergR.d1tdelays = [0,0,83,147,256,344,428,516,827,920];
                    
                    ergR.d3tnaught = [2,11];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170907/20170907_Sq995_Fenretinide';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min11s';...
                        '05_FlashesPost2min37s';...
                        '06_FlashesPost4min03s';...
                        '07_FlashesPost5min28s';...
                        '08_FlashesPost6min53s';...
                        '09_FlashesPost8min20s';...
                        '11_FlashesPost13min42s';...
                        '12_FlashesPost15min10s';...
                        '13_FlashesPost16min36s';...
                        };
                    ergR.d3tdelays = [0,0,71,157,243,328,413,500,822,910,996];
                    
                 case 'Template3'
                    ergR.d1tnaught = [2,7];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = 'dateanddir';
                    ergR.d1dirFile = {...
                        'namehere'; ...
                        };
                    ergR.d1tdelays = [0,0,0,0,0,0,0,0];
                    
                    ergR.d3tnaught = [2,8];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = 'dateanddir';
                    ergR.d3dirFile = {...
                        'namehere';...
                        };
                    ergR.d3tdelays = [0,0,0,0,0,0,0,0];
                %Vehicle
                case 'Sq999'
                    ergR.d1tnaught = [2,7];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170905/20170905_Sq999_Vehicle';
                    ergR.d1dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min18s';...
                        '05_FlashesPost2min43s';...
                        '06_FlashesPost4min08s';...
                        '07_FlashesPost5min32s';...
                        '08_FlashesPost6min58s';...
                        '09_FlashesPost8min24s';...
                        '11_FlashesPost13min14s';...
                        '12_FlashesPost15min32s';...
                        };
                    ergR.d1tdelays = [0,0,78,163,248,332,418,504,794,932];
                    
                    ergR.d3tnaught = [2,10];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170907/20170907_Sq999_Vehicle';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min16s';...
                        '05_FlashesPost2min42s';...
                        '06_FlashesPost4min15s';...
                        '07_FlashesPost5min41s';...
                        '08_FlashesPost7min04s';...
                        '09_FlashesPost8min35s';...
                        '11_FlashesPost14min43s';...
                        '12_FlashesPost16min00s';...
                        };
                    ergR.d3tdelays = [0,0,76,162,255,341,424,515,883,960];
                case 'Sq1000'
%                     ergR.d1tnaught = [2,5];
                    ergR.d1tnaught = [1,5];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170829/20170829_Sq1000_Veh';
                    ergR.d1dirFile = {...
%                         '03_FlahesPre';...
                        '04_FlahesPost0s';...
                        '05_FlahesPost30s';...
                        '06_FlahesPost1min30s';...
                        '07_FlahesPost3min';...
                        '08_FlahesPost5min';...
                        '09_FlahesPost7min15s';...
                        };
%                     ergR.d1tdelays = [0,0,30,90,180,300,435];
                    ergR.d1tdelays = [0,30,90,180,300,435];
                    
                    ergR.d3tnaught = [2,6];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170831/20170831_Sq1000_Vehicle';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost40s';...
                        '05_FlashesPost1min30s';...
                        '06_FlashesPost2min30s';...
                        '07_FlashesPost3min30s';...
                        '08_FlashesPost4min30s';...
                        '09_FlashesPost5min30s';...
                        '10_FlashesPost6min30s';...
                        '11_FlashesPost7min30s';...
                        '12_FlashesPost8min30s';...
                        };
                    ergR.d3tdelays = [0,0,40,90,150,210,270,330,390,450,510];
                case 'Sq992'
                    ergR.d1tnaught = [2,5];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = '20170830/20170830_Sq992_Veh';
                    ergR.d1dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min10s';...
                        '05_FlashesPost2min10s';...
                        '06_FlashesPost3min5s';...
                        '07_FlashesPost4min';...
                        '08_FlashesPost5min10s';...
                        '09_FlashesPost6min20s';...
                        '10_FlashesPost7min40s';...
                        '11_FlashesPost8min45s';...
                        };
                    ergR.d1tdelays = [0,0,70,130,185,240,310,380,460,525];
                    
                    ergR.d3tnaught = [2,9];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = '20170901/20170901_Squirrel992_Vehicle';
                    ergR.d3dirFile = {...
                        '02_FlashesPre';...
                        '03_FlashesPost0s';...
                        '04_FlashesPost1min20s';...
                        '05_FlashesPost2min45s';...
                        '06_FlashesPost4min15s';...
                        '07_FlashesPost5min40s';...
                        '08_FlashesPost7min06s';...
                        '09_FlashesPost8min40s';...
                        '11_FlashesPost13min50s';...
                        };
                    ergR.d3tdelays = [0,0,80,165,255,340,426,520,830];
%                     
%                     
%                     
                case 'Template'
                    ergR.d1tnaught = [2,7];
                    ergR.d1bleachedeye='R';
                    ergR.d1dirData = 'dateanddir';
                    ergR.d1dirFile = {...
                        'namehere'; ...
                        };
                    ergR.d1tdelays = [0,0,0,0,0,0,0,0];
                    
                    ergR.d3tnaught = [2,8];
                    ergR.d3bleachedeye='R';
                    ergR.d3dirData = 'dateanddir';
                    ergR.d3dirFile = {...
                        'namehere';...
                        };
                    ergR.d3tdelays = [0,0,0,0,0,0,0,0];
            end
        end
    end
end



